grails-app/domain/forum/grails/User.groovy
package forum.grails

class User {

    String username
    String password

    Profile profile = new Profile()
    Role role = Role.ROLE_USER

    List<Topic> myTopics
    List<Entry> myEntries

    static hasOne = [
            profile: Profile
    ]

    static hasMany = [
            myTopics: Topic,
            myEntries: Entry
    ]

    static constraints = {
        username unique: true
    }

    boolean equals(o) {
        if (this.is(o)) return true
        if (getClass() != o.class) return false

        User user = (User) o

        if (username != user.username) return false

        return true
    }

    int hashCode() {
        return username.hashCode()
    }

    boolean isAdmin() {
        return role == Role.ROLE_ADMIN
    }
}

grails-app/views/admin/list.gsp
<%--
  Created by IntelliJ IDEA.
  User: Lojza
  Date: 18.4.14
  Time: 23:14
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title>Seznam uživatelů</title>
    <meta name="layout" content="main"/>
</head>

<body>

<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Uživ. jméno</th>
        <th>Jméno</th>
        <th>Příjmení</th>
        <th>Email</th>
        <th>Podpis</th>
        <th>Avatar</th>
    </tr>
    </thead>
    <tbody>
    <g:each in="${userList}" var="user">
        <tr>
            <td>${user.id}</td>
            <td>$${user.username}</td>
            <g:set var="profile" value="${user.profile}"/>
            <th>${profile.firstName}</th>
            <th>${profile.lastName}</th>
            <th>${profile.email}</th>
            <th>${profile.signature}</th>
        </tr>
    </g:each>
    </tbody>
</table>

</body>
</html>