grails-app/domain/forum/grails/Entry.groovy
package forum.grails

class Entry {

    String text
    User author
    Topic topic

    Date dateCreated
    Date lastUpdated

    static belongsTo = Topic

    static constraints = {
        text blank: false
    }

    static mapping = {
        text type: "text"
    }
}

grails-app/controllers/forum/grails/EntryController.groovy
package forum.grails

import org.springframework.transaction.annotation.Propagation

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional
class EntryController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Entry.list(params), model: [entryInstanceCount: Entry.count()]
    }

    def show(Entry entryInstance) {
        Long topicId = entryInstance.topic.id
        redirect controller: "topic", action: "show", id: topicId
    }

    def create() {
        respond new Entry(params)
    }

    @Transactional
    def save(Entry entryInstance) {
        if (entryInstance == null) {
            notFound()
            return
        }

        setAssociations(entryInstance)

        if (!entryInstance.validate()) {
            respond entryInstance.errors, view: 'create'
            return
        }

        entryInstance.save flush: true

        Long topicId = entryInstance.topic.id
        request.withFormat {
            form {
                flash.successMessage = message(code: 'default.created.message', args: [message(code: 'entryInstance.label', default: 'Entry'), entryInstance.id])
                redirect controller: "topic", action: "show", id: topicId
            }
            '*' { respond entryInstance, [status: CREATED] }
        }
    }

    protected void setAssociations(Entry entryInstance) {
        User user = User.get(session.user.id)
        entryInstance.setAuthor(user)
        user.addToMyEntries(entryInstance)
        Topic topic = entryInstance.topic
        topic.addToEntryList(entryInstance)
    }

    def edit(Entry entryInstance) {
        respond entryInstance
    }

    @Transactional
    def update(Entry entryInstance) {
        if (entryInstance == null) {
            notFound()
            return
        }

        if (entryInstance.hasErrors()) {
            respond entryInstance.errors, view: 'edit'
            return
        }

        entryInstance.save flush: true

        request.withFormat {
            form {
                flash.successMessage = message(code: 'default.updated.message', args: [message(code: 'Entry.label', default: 'Entry'), entryInstance.id])
                redirect entryInstance
            }
            '*' { respond entryInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Entry entryInstance) {

        if (entryInstance == null) {
            notFound()
            return
        }

        Long topicId = entryInstance.topic.id
        entryInstance.topic.removeFromEntryList(entryInstance)
        entryInstance.delete flush: true

        request.withFormat {
            form {
                flash.successMessage = message(code: 'default.deleted.message', args: [message(code: 'Entry.label',
                        default: 'Entry'), entryInstance.id])
                redirect controller: "topic", action: "show", id: topicId, method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.errorMessage = message(code: 'default.not.found.message', args: [message(code: 'entryInstance' +
                        '.label', default: 'Entry'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

class EntryCO {
    String text

    static constraints = {
        text blank: false
    }
}

grails-app/views/entry/_form.gsp
<%@ page import="forum.grails.Entry" %>

<bootstrap3:textArea model="${entryInstance}" field="text" id="entry-text"
                     labelName="Text" cols="4" rows="5"/>
<g:hiddenField type="hidden" name="topic.id" id="entry-topic-id" value="${entryInstance.topic.id}"/>

grails-app/views/entry/create.gsp
<%--
  Created by IntelliJ IDEA.
  User: Lojza
  Date: 18.1.14
  Time: 11:16
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title>Přidat příspěvek</title>
    <meta name="layout" content="main"/>
</head>

<body>

<div class="row">
    <g:hasErrors bean="${entryInstance}">
        <span class="help-block">
            <g:renderErrors bean="${entryInstance}"/>
        </span>
    </g:hasErrors>

    <g:form method="post" resource="${entryInstance}" action="save">
        <fieldset>
            <legend>${g.message(code: "default.create.label", args: ["příspěvek"])}</legend>
            <g:render template="form" model="[entryInstance: entryInstance]"/>
        </fieldset>
        <input value="Uložit" type="submit" class="btn btn-primary"/>
    </g:form>
</div>

</body>
</html>

grails-app/views/entry/edit.gsp
<%--
  Created by IntelliJ IDEA.
  User: Lojza
  Date: 18.1.14
  Time: 11:16
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title>Upravit příspěvek ${entryInstance.id}</title>
    <meta name="layout" content="main"/>
</head>

<body>

<div class="row">
    <g:hasErrors bean="${entryInstance}">
        <span class="help-block">
            <g:renderErrors bean="${entryInstance}"/>
        </span>
    </g:hasErrors>

    <g:form method="put" resource="${entryInstance}" action="update">
        <fieldset>
            <legend>${entryInstance.id}</legend>
            <g:if test="${entryInstance.id}">
                <g:hiddenField name="version" value="${entryInstance.version}"/>
                <g:hiddenField name="id" value="${entryInstance.id}"/>
            </g:if>
            <g:render template="form" model="[entryInstance: entryInstance]"/>
        </fieldset>
        <g:actionSubmit value="Aktualizovat" action="update" type="submit" class="btn btn-primary"/>
    </g:form>
</div>

</body>
</html>

grails-app/views/entry/index.gsp
<%@ page import="forum.grails.Entry" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'entry.label', default: 'Entry')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-entry" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-entry" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="text" title="${message(code: 'entry.text.label', default: 'Text')}" />
					
						<th><g:message code="entry.author.label" default="Author" /></th>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'entry.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'entry.lastUpdated.label', default: 'Last Updated')}" />
					
						<th><g:message code="entry.topic.label" default="Topic" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${entryInstanceList}" status="i" var="entryInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${entryInstance.id}">${fieldValue(bean: entryInstance, field: "text")}</g:link></td>
					
						<td>${fieldValue(bean: entryInstance, field: "author")}</td>
					
						<td><g:formatDate date="${entryInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${entryInstance.lastUpdated}" /></td>
					
						<td>${fieldValue(bean: entryInstance, field: "topic")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${entryInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/entry/show.gsp
<%@ page import="forum.grails.Entry" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'entry.label', default: 'Entry')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-entry" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                            default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-entry" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list entry">

        <g:if test="${entryInstance?.text}">
            <li class="fieldcontain">
                <span id="text-label" class="property-label"><g:message code="entry.text.label" default="Text"/></span>

                <span class="property-value" aria-labelledby="text-label"><g:fieldValue bean="${entryInstance}"
                                                                                        field="text"/></span>

            </li>
        </g:if>

        <g:if test="${entryInstance?.author}">
            <li class="fieldcontain">
                <span id="author-label" class="property-label"><g:message code="entry.author.label"
                                                                          default="Author"/></span>

                <span class="property-value" aria-labelledby="author-label"><g:link controller="user" action="show"
                                                                                    id="${entryInstance?.author?.id}">${entryInstance?.author?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${entryInstance?.dateCreated}">
            <li class="fieldcontain">
                <span id="dateCreated-label" class="property-label"><g:message code="entry.dateCreated.label"
                                                                               default="Date Created"/></span>

                <span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate
                        date="${entryInstance?.dateCreated}"/></span>

            </li>
        </g:if>

        <g:if test="${entryInstance?.lastUpdated}">
            <li class="fieldcontain">
                <span id="lastUpdated-label" class="property-label"><g:message code="entry.lastUpdated.label"
                                                                               default="Last Updated"/></span>

                <span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate
                        date="${entryInstance?.lastUpdated}"/></span>

            </li>
        </g:if>

        <g:if test="${entryInstance?.topic}">
            <li class="fieldcontain">
                <span id="topic-label" class="property-label"><g:message code="entry.topic.label"
                                                                         default="Topic"/></span>

                <span class="property-value" aria-labelledby="topic-label"><g:link controller="topic" action="show"
                                                                                   id="${entryInstance?.topic?.id}">${entryInstance?.topic?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: entryInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${entryInstance}"><g:message code="default.button.edit.label"
                                                                                      default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>